openapi: 3.0.3
info: 
  title: Lot API
  version: 0.2.0 
  license:
    name: Confidential
    url: https://yourdomain.com/license
servers: [ { url: /lot } ]
security:
  - bearerAuth: []
paths:
  /lots:
    get:
      operationId: getAllLots
      summary: Retrieve all lots with pagination
      responses: 
        '200': { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/LotPage' }}}}
        '400':
          description: Invalid query parameters
        '401':
          description: Unauthorized request
        '403':
          description: Forbidden — insufficient permissions
        '404':
          description: No lots found
    post:
      operationId: createLot
      summary: Create a new lot record
      requestBody: { required: true, content: { application/json: { schema: { $ref: '#/components/schemas/LotCreate' }}}}
      responses: 
        '201': { description: Created } 
        '400':
          description: Invalid request data
        '401':
          description: Unauthorized request
components:
  securitySchemes:
    bearerAuth: {type: http, scheme: bearer, bearerFormat: JWT}
  schemas:
    Lot:
      type: object
      required: [id,productId,sourceActorId,harvestedAt,quantity,unit,status]
      properties:
        id: { type: string, format: uuid }
        productId: { type: string, format: uuid }
        sourceActorId: { type: string, format: uuid }
        harvestedAt: { type: string, format: date-time }
        quantity: { type: number, minimum: 0 }
        unit: { type: string, enum: [KG,G,L] }
        status: { type: string, enum: [CREATED,AVAILABLE,IN_TRANSFER,CONSUMED] }
    LotCreate:
      type: object
      required: [productId,sourceActorId,harvestedAt,quantity,unit]
      properties:
        productId: { type: string, format: uuid }
        sourceActorId: { type: string, format: uuid }
        harvestedAt: { type: string, format: date-time }
        quantity: { type: number, minimum: 0 }
        unit: { $ref: '#/components/schemas/Lot/properties/unit' }
    LotPage:
      type: object
      properties:
        content: { type: array, items: { $ref: '#/components/schemas/Lot' } }
        page: { type: integer }
        size: { type: integer }
        totalElements: { type: integer }
